SELECT a.CATEGORY, a.PRICE AS MAX_PRICE, a.PRODUCT_NAME
FROM FOOD_PRODUCT a
JOIN (
    SELECT CATEGORY, MAX(PRICE) AS PRICE
    FROM FOOD_PRODUCT
    WHERE CATEGORY IN ('과자', '국', '김치', '식용유')
    GROUP BY CATEGORY
) b
ON a.CATEGORY = b.CATEGORY
AND a.PRICE = b.PRICE
ORDER BY MAX_PRICE DESC