-- UNION
SELECT CAR_ID, "대여중" AS AVAILABILITY  
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE DATE(START_DATE) <= DATE("2022-10-16") 
AND DATE(END_DATE) >= DATE("2022-10-16")

UNION

SELECT CAR_ID, "대여 가능" AS AVAILABILITY  
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE CAR_ID NOT IN (SELECT CAR_ID
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE DATE(START_DATE) <= DATE("2022-10-16") 
AND DATE(END_DATE) >= DATE("2022-10-16"))

ORDER BY CAR_ID DESC;

-- EXISTS
SELECT CAR_ID,
CASE
    WHEN EXISTS (
        SELECT 1 FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY a
        WHERE a.CAR_ID = b.CAR_ID
        AND DATE(START_DATE) <= DATE("2022-10-16")
        AND DATE(END_DATE) >= DATE("2022-10-16")
    ) THEN '대여중'
    ELSE '대여 가능'
END AS AVAILABILITY
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY b
GROUP BY CAR_ID
ORDER BY CAR_ID DESC;