SELECT 
b.AUTHOR_ID, 
a.AUTHOR_NAME, 
b.CATEGORY, 
SUM(bs.SALES * b.PRICE) AS TOTAL_SALES 
FROM BOOK b
JOIN AUTHOR a ON a.AUTHOR_ID = b.AUTHOR_ID
JOIN BOOK_SALES bs ON bs.BOOK_ID = b.BOOK_ID
WHERE DATE(bs.SALES_DATE) >= DATE("2022-01-01")
AND DATE(bs.SALES_DATE) < DATE("2022-02-01")
GROUP BY b.AUTHOR_ID, b.CATEGORY
ORDER BY b.AUTHOR_ID, b.CATEGORY DESC