-- 날짜 추출 함수 (YEAR(), MONTH(), DAY())
-- 날짜 형식 변환 (DATE_FORMAT(컬럼, '형식'))
SELECT BOOK_ID, DATE_FORMAT(PUBLISHED_DATE, '%Y-%m-%d') AS 'PUBLISHED_DATE' FROM BOOK
WHERE YEAR(PUBLISHED_DATE) = 2021
AND CATEGORY = '인문'
ORDER BY PUBLISHED_DATE ASC;
