  SELECT a.FOOD_TYPE, a.REST_ID, a.REST_NAME, a.FAVORITES
  FROM REST_INFO a
  JOIN (
    SELECT FOOD_TYPE, MAX(FAVORITES) AS MAX_FAV
    FROM REST_INFO
    GROUP BY FOOD_TYPE
  ) b
    ON a.FOOD_TYPE = b.FOOD_TYPE
   AND a.FAVORITES = b.MAX_FAV
  ORDER BY a.FOOD_TYPE DESC;
-- ROW_NUMBER()
SELECT t.FOOD_TYPE, t.REST_ID, t.REST_NAME, t.FAVORITES
  FROM (
      SELECT 
      r.*,
      ROW_NUMBER() OVER (PARTITION BY FOOD_TYPE ORDER BY FAVORITES DESC) AS rk
      FROM REST_INFO r
  ) t
  WHERE t.rk = 1
  ORDER BY t.FOOD_TYPE DESC;